# SPDX-FileCopyrightText: 2022 Jakub Wasylków <kuba_160@protonmail.com>
# SPDX-License-Identifier: CC0-1.0

name: ddb_discord_presence plugin build

on: [push,pull_request]

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Get sha_short
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Download DeaDBeeF header
      run: wget https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/1.8/deadbeef.h && mkdir deadbeef && mv deadbeef.h deadbeef/
    - name: Build ddb_discord_presence
      run: make && mkdir binary && make install PREFIX=./binary
    - name: Build ddb_discord_presence with debugging symbols
      run: make clean && make DEBUG=1 && mkdir binary_debug && make install PREFIX=./binary_debug
    - name: Upload artifact linux-${{ steps.vars.outputs.sha_short }}.zip
      uses: actions/upload-artifact@v3
      if: ${{ !env.ACT }}
      with:
        name: linux-${{ steps.vars.outputs.sha_short }}
        path: ./binary
    - name: Upload artifact linux-debug-${{ steps.vars.outputs.sha_short }}.zip
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v3
      with:
        name: linux-debug-${{ steps.vars.outputs.sha_short }}
        path: ./binary_debug

  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v1
     - name: Get sha_short
       id: vars
       run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
     - name: Install msys2
       uses: msys2/setup-msys2@v2
       with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc wget make git patch tar
     - name: Download DeaDBeeF header
       shell: msys2 {0}
       run: wget https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/1.8/deadbeef.h && mkdir deadbeef && mv deadbeef.h deadbeef/
     - name: Build ddb_discord_presence
       shell: msys2 {0}
       run: make && mkdir binary && make install PREFIX=./binary
     - name: Build ddb_discord_presence with debugging symbols
       shell: msys2 {0}
       run: make clean && make DEBUG=1 CC=gcc && mkdir binary_debug && make install PREFIX=./binary_debug
     - name: Upload artifact windows-${{ steps.vars.outputs.sha_short }}.zip
       uses: actions/upload-artifact@v3
       with:
         name: windows-${{ steps.vars.outputs.sha_short }}
         path: ./binary
     - name: Upload artifact windows-debug-${{ steps.vars.outputs.sha_short }}.zip
       uses: actions/upload-artifact@v3
       with:
         name: windows-debug-${{ steps.vars.outputs.sha_short }}
         path: ./binary_debug

